pipeline:
  name: testings3cfn
  identifier: testings3cfn
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: testcfn
        identifier: testcfn
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1dsa
                  identifier: CreateStack_1
                  timeout: 10m
                  spec:
                    provisionerIdentifier: stackcreate
                    configuration:
                      stackName: testings3bucket
                      connectorRef: account.Aws_Login
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - harnesstest.yml
                              connectorRef: account.Github
                              repoName: Demo
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
        tags: {}
