pipeline:
  name: testings3bucketins3
  identifier: testings3bucketins3
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Creates3stackusingparamter
        identifier: Creates3stackusingparamter
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: createstacks3usings3
                    configuration:
                      stackName: creates3stackusings3
                      connectorRef: Aws
                      region: us-east-2
                      templateFile:
                        type: S3URL
                        spec:
                          templateUrl: https://testingforharness.s3.us-east-2.amazonaws.com/CF+test/test.yaml
                      roleArn: ""
                      parameters:
                        - identifier: S3BucketParameter
                          store:
                            type: S3Url
                            spec:
                              connectorRef: Aws
                              urls:
                                - https://testingforharness.s3.us-east-2.amazonaws.com/CF+test/testparams.json
                              region: us-east-2
                      parameterOverrides: []
                  timeout: 10m
        tags: {}
